language: android
android:
  components:
    # The BuildTools version used by your project
    - build-tools-26.1

    # The SDK version used to compile your project
    - android-26
  licenses:
    - 'android-sdk-license-.+'

before_install:
 - chmod +x gradlew
 - yes | sdkmanager "platforms;android-26"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
